config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get "/dashboard", to: "dashboard#index"

  get "/auth/:provider/callback", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout

  resources :users
  resources :teams do
    resources :posts
    post "/posts/:id/tweet", to: "posts#tweet", as: :tweet_post
  end

  post "/teams/:id/join", to: "teams#join", as: :join_team
  post "/teams/:id/leave", to: "teams#leave", as: :leave_team
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, scope: :provider

  def self.find_for_auth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
   belongs_to :user
   belongs_to :team
end

# == Schema Information
#
# Table name: memberships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  team_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  validates :tweet, presence: true
  validates :planned_time, presence: true
end

# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  tweet        :text
#  user_id      :integer
#  planned_time :datetime
#  created_at   :datetime
#  updated_at   :datetime
#  team_id      :integer
#

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :owner, class_name: "User", foreign_key: "user_id", touch: true
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :posts

  validates :name, presence: true
end

# == Schema Information
#
# Table name: teams
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  user_id     :integer
#

app/models/user.rb
class User < ActiveRecord::Base
  attr_encrypted :twitter_token, key: ENV["ENCRYPTED_USER_DATA_KEY"]
  attr_encrypted :twitter_secret, key: ENV["ENCRYPTED_USER_DATA_KEY"]

  validates :name, presence: true
  validates :uid, presence: true
  validates :provider, presence: true
  validates :twitter_handle, presence: true

  has_many :posts
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image_url = auth["info"]["image"]
      user.twitter_handle = auth["info"]["nickname"]
      user.twitter_token = auth["credentials"]["token"]
      user.twitter_secret = auth["credentials"]["secret"]
    end
  end

  def twitter_url
    "https://www.twitter.com/@" + twitter_handle
  end
end

# == Schema Information
#
# Table name: users
#
#  id                       :integer          not null, primary key
#  provider                 :string
#  uid                      :string
#  name                     :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  image_url                :string
#  encrypted_twitter_token  :string
#  encrypted_twitter_secret :string
#  twitter_handle           :string
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_team


  def authorize
    redirect_to root_path, alert: "Not authorized" if current_user.nil?
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_team
    @current_team ||= Team.find(params[:team_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @teams = current_user.teams
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to dashboard_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :check_team, only: [:new, :create]

  def index
    @posts = Post.where team: current_team
  end

  def new
    @post = Post.new(user: current_user, team: current_team)
  end

  def create
    @post = current_team.posts.new(post_params)
    @post.user = current_user

    if @post.save!
      redirect_to team_post_path(@post.team, @post)
    else
      render :new
    end
  end

  def show
    resource
  end

  def edit
    resource
  end

  def update
    resource.update_attributes(post_params)
    redirect_to team_post_path(resource.team, resource)
  end

  def destroy
    resource.destroy
    redirect_to team_posts_path
  end

  def tweet
    initialize_twitter_client.update(resource.tweet)
    redirect_to team_posts_path, notice: "tweet sent"
  end

  private

  def resource
    @post ||= Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:tweet, :planned_time)
  end

  def correct_user
    @user = resource.user
    unless @user == current_user
      redirect_to team_posts_path, notice: "Not authorized"
    end
  end

  def check_team
    unless current_team.users.include?(current_user)
      redirect_to team_path(current_team)
    end
  end

  def initialize_twitter_client
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['TWITTER_KEY']
      config.consumer_secret = ENV['TWITTER_SECRET']
      config.access_token = resource.team.owner.twitter_token
      config.access_token_secret = resource.team.owner.twitter_secret
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "welcome!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "logged out!"
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  helper_method :is_member
  before_filter :authorize
  before_action :correct_user, only: [:edit, :update, :destroy]

 def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    @team.owner = current_user

    if @team.save
      create_membership(current_user, @team)
      redirect_to team_path(@team)
    else
      flash[:error] = t("teams.fail")
      render :new
    end
  end

  def show
    resource
  end

  def edit
    resource
  end

  def update
    resource.update_attributes(team_params)
    redirect_to team_path(resource)
  end

  def destroy
    resource.destroy
    redirect_to teams_path
  end

  def join
    if create_membership(current_user, resource)
      redirect_to team_path(resource)
    else
      render :show, notice: "Something went wrong"
    end
  end

  def leave
    @membership = current_user.memberships.find_by_team_id(resource.id)
    @membership.destroy!
    redirect_to team_path(resource)
  end


  private

  def resource
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name, :description)
  end

  def correct_user
    @user = resource.owner
    unless @user == current_user
      redirect_to teams_path, notice: "Not authorized"
    end
  end

  def is_member
    resource.users.include?(current_user)
  end

  def create_membership(user, team)
    @membership = Membership.new
    @membership.user = user
    @membership.team = team
    @membership.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    resource.update_attributes(user_params)
    redirect_to user_path(resource)
  end

  private

  def resource
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to users_path, notice: "Not authorized"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_navigation.html.erb
<nav class="navigation" role="navigation">
  <section class="wrap">
      <%= link_to root_path do %>
        <%= image_tag "eggplant.png", class: "logo" %>
        <span class="logo-text">Eggplant</span>
      <% end %>
    <span class="user-menu pull-right">
      <% if current_user %>
        <%= link_to t("navigation.teams"), teams_path %>
        <%= link_to user_path(current_user) do %>
          <%= image_tag current_user.image_url, class: "avatar" %>
        <% end %>
        <%= link_to t("navigation.sign_out"), signout_path, class: "button" %>
      <% else %>
        <%= link_to t("navigation.sign_in_with_twitter"), "/auth/twitter", class: "button" %>
      <% end %>
    </span>
  </section>
</nav>

app/views/dashboard/index.html.erb
<h1><%= t("dashboard") %></h1>
<div>
  <% @teams.each do |team| %>
  <div>
    <h2>
      <%= link_to team.name, team_path(team) %>
    </h2>

    <% team.posts.first(5).each do |post| %>
      <div class="tweet">
        <%= link_to post.tweet, team_post_path(post.team, post) %>
        <%= button_to t("actions.tweet"), team_tweet_post_path(post.team, post) %>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eggplant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render "navigation" %>
</header>

<div class="wrap container" role="main">
  <%= yield %>
</div>

<%= render "refills/flashes" %>
</body>
</html>

app/views/posts/edit.html.erb
<div>
  <%= link_to t("posts.back_to_all_posts", team_name: @post.team.name), team_posts_path(current_team) %>
</div>
<h1><%= t("posts.edit") %></h1>
<hr>
<%= form_for @post, url: team_post_path do |f| %>
  <div class="tweet">
    <%= f.label t("posts.tweet") %>
    <%= f.text_area :tweet %>
  </div>

  <div class="planned-time">
    <%= f.label t("posts.planned_time") %>
    <%= f.datetime_select :planned_time %>
  </div>
  <%= f.submit class: "button" %>
<% end %>

app/views/posts/index.html.erb
<div>
  <%= link_to t("teams.back_to_team", team_name: current_team.name), team_path(current_team) %>
  <h1><%= t("teams.posts_for") %> for <%= current_team.name %></h1>
  <% @posts.each do |post| %>
  <div>
    <%= link_to post.tweet, team_post_path(post.team, post) %>
  </div>
  <% end %>
  <p>
    <%= link_to t("posts.new_post"), new_team_post_path, class: "button" %>
  </p>
</div>

app/views/posts/new.html.erb
<div>
  <%= link_to t("posts.back_to_all_posts", team_name: @post.team.name), team_posts_path(current_team) %>
</div>
<%= form_for @post, url: team_posts_path do |f| %>
  <div class="tweet">
    <%= f.label t("posts.tweet") %>
    <%= f.text_area :tweet %>
  </div>

  <div class="planned-time">
    <%= f.label t("posts.planned_time") %>
    <%= f.datetime_select :planned_time %>
  </div>
  <%= f.submit class: "button" %>
<% end %>

app/views/posts/show.html.erb
<div>
  <div>
    <%= link_to t("posts.back_to_all_posts", team_name: @post.team.name), team_posts_path(current_team) %>
  </div>
  <%= @post.tweet %><br>
  <%= @post.planned_time %><br>
  <%= link_to t("actions.edit"), edit_team_post_path(@post.team, @post) %> |
  <%= link_to t("actions.delete"), team_post_path(@post.team, @post), method: :delete %>
  <p>
    <%= button_to t("actions.tweet"), team_tweet_post_path(@post.team, @post), class: "button" %>
  </p>
</div>

app/views/refills/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="flash-<%= key %>">
    <span><%= value %></span>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t("users.edit_profile") %></h1>

<%= image_tag @user.image_url %>

<%= form_for(@user) do |f| %>


  <%= f.label t("users.name") %>
  <%= f.text_field :name %>

  <%= f.submit t("actions.save"), class: "button" %>
<% end %>

app/views/users/index.html.erb
<div>
  <h1><%= t("users.all_users") %></h1>
  <% @users.each do |user| %>
    <div class="user">
      <%= image_tag user.image_url, class: "avatar small" %>
      <%= user.name %>
      <% if current_user.id == user.id %>
        (<%= link_to t("users.edit_profile"), edit_user_path(user) %>)
      <% end %>
    <hr>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
  <h1><% t("user.profile") %></h1>
  <%= @user.name %>
  <hr>
  <%= image_tag @user.image_url, class: "avatar" %>
  <% if current_user.id == @user.id %>
    <%= link_to t("user.edit_profile"), edit_user_path(@user) %>
  <% end %>

</div>